name: Build Redemption Loader
run-name: ${{ inputs.release == true && 'Release' || 'Build' }} for ${{ inputs.ipa_url || 'local' }}

on:
  workflow_dispatch:
    inputs:
      ipa_url:
        description: "Direct link to the decrypted ipa"
        required: true
        type: string
      release:
        description: "Create a GitHub release"
        default: true
        type: boolean
      is_testflight:
        description: "This is a TestFlight build"
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Theos
        run: |
          sudo apt-get update
          sudo apt-get install -y ldid
          git clone --recursive https://github.com/theos/theos.git /opt/theos
          echo "export THEOS=/opt/theos" >> ~/.bashrc
          echo "export PATH=$PATH:$THEOS/bin" >> ~/.bashrc
          source ~/.bashrc

      - name: Build Tweak
        run: |
          export THEOS=/opt/theos
          make package

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Redemption-Loader-deb
          path: packages/*.deb

      - name: Create Release (Optional)
        if: ${{ inputs.release == true }}
        uses: softprops/action-gh-release@v1
        with:
          files: packages/*.deb
          name: Redemption Loader Release ${{ github.run_number }}
          tag_name: v${{ github.run_number }}
          body: | 
            Automated release of Redemption Loader build ${{ github.run_number }}
            Built from commit ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
