name: Build validation

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write

jobs:
  build-check:
    name: Build Check
    uses: ./.github/workflows/build.yml
    with:
      release: false
      caller_workflow: "ci"
    secrets: inherit