name: PR Assignment

permissions:
  pull-requests: write
  issues: write

on:
    pull_request:
        types: [opened, edited, synchronize, reopened]

jobs:
    auto-assign:
        runs-on: ubuntu-latest
        steps:
            - name: 'Auto-assign PR'
              uses: pozil/auto-assign-issue@v2
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  assignees: acquitelol,marioparaschiv
                  numOfAssignee: 2
